### ISSUE TITLE
connect is not a function

### ISSUE THREAD

**Issue by nohanmohsin** [BIntelligent/currency-system#1]
I am using the connect function from the currency system and I am getting an error
`TypeError: connect is not a function`

the code:
`const cs = new CurrencySystem;
const {connect} = CurrencySystem;
connect(process.env.MONGO_DB_URL);`
I am pretty dumb so it might be an easy thing T^T

**Comment by BIntelligent** [comment]
Hey, hope you're doing well. I never though someone will be using my package lol I am now motivated to work on it Thanks and for your issue here's the answer you have wrong code. 
source to example bot: https://github.com/BIntelligent/currency-system/blob/main/ExampleBot/src/index.js
it should be 
```js
const { connect }  = require("currency-system");
connect(process.env.MONGO_DB_URL);

**Comment by BIntelligent** [comment]
you can dm me at discord ( Be Intelligent#0001 ) for fast replies

**Comment by nohanmohsin** [comment]
hey 😅 the discord account tag doesnt work. can you check it??
and thanks for developing this package :3 helps aloooooooooooooooooot

**Comment by nohanmohsin** [comment]
lmaaaaaaoooooooooooooooooooooooooooo I got it fixed bro!!!!!!

the solution:
```const CurrencySystem = require("currency-system");
const cs = new CurrencySystem;
const connect = cs.connect;
connect(process.env.MONGO_DB_URL);
```
and again thank you so so much for the package!!! now I am so productive :33333333 thanks so much bro
imma close the issue

**Comment by BIntelligent** [comment]
np man it was my first package and anything you want custom built-in? i can do it for you and 
![image](https://user-images.githubusercontent.com/65684589/116915558-9a940b80-ac65-11eb-8513-48cdf9a86ee9.png)

**Comment by BIntelligent** [comment]
join this, you'll find me https://discord.gg/c98ah8YUMd
