### ISSUE TITLE
on the rob command, user.bot is undefined.

### ISSUE THREAD

**Issue by SmugTheKiler** [BIntelligent/currency-system#11]
user.bot undefined.

**Comment by BIntelligent** [comment]
hi, I don't think thats a issue with my package maybe send the whole error. I'll help you with it

**Comment by SmugTheKiler** [comment]
oh, never mind, but I would suggest you to edit it to provent other users from running into the error.

Move the `if bot` checker under the thing where you check if the user has mentioned someone, because the user can simply put no one and that will spam the terminal since you can't check no one if they are a bot.. because they are no one. So simply move if(user.bot | client.bot) under if(!user) .

**Comment by BIntelligent** [comment]
you were the first person amongst 10,000 people to get that. but Ok Thanks.
