### ISSUE TITLE
Global shop error

### ISSUE THREAD

**Issue by SmugTheKiler** [BIntelligent/currency-system#12]
``UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'guild' of undefined
18.08 13:47:11 [Bot] Startup at getInventory (/node_modules/currency-system/src/classes/functions.js:701:19)
18.08 13:47:11 [Bot] Startup at CurrencySystem.getShopItems (/node_modules/currency-system/src/classes/functions.js:657:22)
18.08 13:47:11 [Bot] Startup at Object.execute (/Bot1/commands/economy/shop.js:13:28)
18.08 13:47:11 [Bot] Startup at Client.<anonymous> (/Bot1/index.js:470:15)
18.08 13:47:11 [Bot] Startup at Client.emit (events.js:310:20)``

This is the error when u try to do getShopItems() function without the guild. And as it said on the website, you have to remove all guild message stuff to make it global.

**Comment by BIntelligent** [comment]
hi, show your code.

**Comment by BIntelligent** [comment]
it should be like this ```
let result = await cs.getShopItems({
        guild: message.guild
    });```
 or ```
let result = await cs.getShopItems({});```

**Comment by SmugTheKiler** [comment]
oh... so it has to have `{}` 
? Alright thanks

**Comment by BIntelligent** [comment]
np, did it work?

**Comment by SmugTheKiler** [comment]
No.
It still just says "shop" with no shop items when I added em

**Comment by BIntelligent** [comment]
well i know shop is not fully working because mongoose.. I'll update to mongodb soon

**Comment by SmugTheKiler** [comment]
good...
