### ISSUE TITLE
Is this only meant for Discord Bots?

### ISSUE THREAD

**Issue by LuckyYam** [BIntelligent/currency-system#14]
Hey! I just used your module in my WhatsApp Bot, it worked but the problem was that all of the users share the same balance, cooldown and everything. Can you please look into it?

**Comment by BIntelligent** [comment]
hello, how do you define userID?

**Comment by BIntelligent** [comment]
userID must be unique for every user e.g you can use there phone number as there ID!

**Comment by LuckyYam** [comment]
All of them are different.

**Comment by LuckyYam** [comment]
Thanks for the fast reply.

**Comment by gamingrkp** [comment]
> Thanks for the fast reply.

you need change the function first from settings.user.id to settings.user  and use sender

**Comment by BIntelligent** [comment]
did it work?

**Comment by BIntelligent** [comment]
and for settings.user to give there id just do
user: { id: "some id" }

and the reason for fast reply is... https://discord.gg/qtZpw7S7

**Comment by LuckyYam** [comment]
> and for settings.user to give there id just do user: { id: "some id" }
> 
> and the reason for fast reply is... https://discord.gg/qtZpw7S7

Thanks! I did what you told me to and it worked.

**Comment by BIntelligent** [comment]
good, glad it worked.
