### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by ManicModder** [BIntelligent/currency-system#15]
You don't say how to install all the dependencies anywhere that I can find like the I know how to install mongoose and discord.js as well as the currency system dependencies but the other ones I have never heard of and am having trouble finding out how to install

**Comment by BIntelligent** [comment]
which dependencies? just `npm i <name>`

**Comment by BIntelligent** [comment]
oh wait ig you're talking about the example bot?, it has un-used dependencies which i just removed.

**Comment by ManicModder** [comment]
Alright thank I got it all working now and I have to say you're a legend I've been looking for something like this for a long time now then your github guide showed up on google search and it's exactly what I needed
