### ISSUE TITLE
Discord API error

### ISSUE THREAD

**Issue by ManicModder** [BIntelligent/currency-system#16]
Hi I don't mean to be a bother but I have got the bot up and running and am now encountering this issue when trying to add items to the shop I was wondering if it's something I have done wrong also I would like to know if there is a way around this by manually coding in new items and if not how do I fix this error I am extremely new to coding and have a very limited understanding of this error information and of coding in general but I figure the best person to ask would be you 

DiscordAPIError: Unknown interaction
    at RequestHandler.execute (c:\Users\danie\Desktop\CurrencyBot\node_modules\discord.js\src\rest\RequestHandler.js:349:13)
    at processTicksAndRejections (c:\Users\danie\Desktop\CurrencyBot\lib\internal\process\task_queues.js:96:5)
    at async RequestHandler.push (c:\Users\danie\Desktop\CurrencyBot\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async CommandInteraction.deferReply (c:\Users\danie\Desktop\CurrencyBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:57:5)
    at async Object.exports.run (c:\Users\danie\Desktop\CurrencyBot\src\commands\additem.js:5:5)
    at async Client.<anonymous> (c:\Users\danie\Desktop\CurrencyBot\src\index.js:64:9) {name: 'DiscordAPIError', message: 'Unknown interaction', method: 'post', path: '/interactions/925304153104855060/aW50ZXJhY3Rpb…SzN5MW5iNkY0Yk1DbnRwaHFRQVpocXluZHVi/callback', code: 10062, …}
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (c:\Users\danie\Desktop\CurrencyBot\node_modules\discord.js\src\rest\RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (c:\Users\danie\Desktop\CurrencyBot\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async CommandInteraction.reply (c:\Users\danie\Desktop\CurrencyBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:99:5)
====================

**Comment by BIntelligent** [comment]
hello, inventory seems to be buggy for some people. and that error looks like djs error, contact them. https://discord.gg/djs

**Comment by ManicModder** [comment]
Hi sorry to bother you again but I have more information on the issue it's apparently because I need to add deferReply() or something so I have more time to respond but I am unsure where to add this and how, I figured cause you're the creator you might know i did check it does have deferReply apart of the code which is really confusing to me because that's what I have been told to add, do I need to set a time or something

**Comment by BIntelligent** [comment]
can i see your code?

**Comment by ManicModder** [comment]
That's the code I was first using I was advised to change it so that message and args is replaced with interaction and all instances of message have been changed to interaction but that make no difference in the error that shows up so I switched back to this originalcode straight from git hub

const Discord = require('discord.js')
const CurrencySystem = require("currency-system");
const cs = new CurrencySystem;
exports.run = async (client, message, args) => {
    await message.deferReply();
    if (message.options.getInteger('price') < 1) return message.editReply("You can't add an item for less than 1$!");
    let result = await cs.addItem({
        guild: message.guild,
        inventory: {
            name: message.options.getString('name'),
            price: message.options.getInteger('price'),
            description: message.options.getString('description') || 'No Description'
        }
    });
    if (result.error) {
        if (result.type == 'No-Inventory-Name') return message.editReply('There was a error, Please enter item name to add.!')
        if (result.type == 'Invalid-Inventory-Price') return message.editReply('There was a error, invalid price!')
        if (result.type == 'No-Inventory-Price') return message.editReply('There was a error, You didnt specify price!')
        if (result.type == 'No-Inventory') return message.editReply('There was a error, No data recieved!')
    } else return message.editReply('Done! Successfully added `' + message.options.getString('name') + '` to the shop!')



}

exports.help = {
    name: "additem",
    data: {
        name: 'additem',
        description: "A way to additem to shop",
        options: [{
                name: 'name',
                type: 'STRING',
                description: 'Name of Item.',
                required: true,
            }, {
                name: 'price',
                type: 'INTEGER',
                description: 'Price of item',
                required: true,
            },

            {
                name: 'description',
                type: 'STRING',
                description: 'Description of the item. (Can\'t be Changed later.)',
                required: false,
            }
        ]
    }
};

exports.conf = {
    aliases: [],
    cooldown: 5 // This number is a seconds, not a milliseconds.
    // 1 = 1 seconds.
}

**Comment by BIntelligent** [comment]
try console.log(result) before if (error)... line btw you know you can use \```js just like discord

**Comment by ManicModder** [comment]
Did you mean like that sorry about before I actually didn't realize how to format code here and I've added in the console log but I'm unsure if that's how I was supposed to do it

```const Discord = require('discord.js')
const CurrencySystem = require("currency-system");
const cs = new CurrencySystem;
exports.run = async (client, message, args) => {
    await message.deferReply();
    if (message.options.getInteger('price') < 1) return message.editReply("You can't add an item for less than 1$!");
    let result = await cs.addItem({
        guild: message.guild,
        inventory: {
            name: message.options.getString('name'),
            price: message.options.getInteger('price'),
            description: message.options.getString('description') || 'No Description'
        }
    });
    console.log(result)
    if (result.error) {
        if (result.type == 'No-Inventory-Name') return message.editReply('There was a error, Please enter item name to add.!')
        if (result.type == 'Invalid-Inventory-Price') return message.editReply('There was a error, invalid price!')
        if (result.type == 'No-Inventory-Price') return message.editReply('There was a error, You didnt specify price!')
        if (result.type == 'No-Inventory') return message.editReply('There was a error, No data recieved!')
    } else return message.editReply('Done! Successfully added `' + message.options.getString('name') + '` to the shop!')



}

exports.help = {
    name: "additem",
    data: {
        name: 'additem',
        description: "A way to additem to shop",
        options: [{
                name: 'name',
                type: 'STRING',
                description: 'Name of Item.',
                required: true,
            }, {
                name: 'price',
                type: 'INTEGER',
                description: 'Price of item',
                required: true,
            },

            {
                name: 'description',
                type: 'STRING',
                description: 'Description of the item. (Can\'t be Changed later.)',
                required: false,
            }
        ]
    }
};

exports.conf = {
    aliases: [],
    cooldown: 5 // This number is a seconds, not a milliseconds.
    // 1 = 1 seconds.
}```

**Comment by BIntelligent** [comment]
what does console log?

**Comment by ManicModder** [comment]
---------------------------------------------------
| @ currency-system                        - [] X |
---------------------------------------------------
|            The module is out of date!           |
|             New version is available!           |
|                2.6.39 --> 2.6.40                |
|        Run "npm i currency-system@latest"       |
|                    to update!                   |
|          View the full changelog here:          |
|         https://currency-system.js.org          |
---------------------------------------------------

**Comment by ManicModder** [comment]
so i'm guessing i need to update yeh

**Comment by BIntelligent** [comment]
yes update but turn bot on, re use the addItem command and than it should log something in console

**Comment by ManicModder** [comment]
sorry this might be a stupid question but do I run the update with the bot on or do I turn it off to update it and then turn it back on

**Comment by BIntelligent** [comment]
turn bot off, update package than turn bot on

**Comment by ManicModder** [comment]
[ CS => Debug ] : UpdateInventory function is executed.
{
  error: false,
  item: { name: 'shotgun', price: 10000, description: 'No Description' }
}
[ CS => Debug ] : Connected to MongoDB ( updateInventory Function )
[ CS => Debug ] : Successfully Saved Data ( updateInventory Function )
[ CS => Debug ] : Closing DB  ( updateInventory Function )

**Comment by BIntelligent** [comment]
so it added the item successfully

**Comment by ManicModder** [comment]
Well it says it has been added and that error isn't occurring anymore but it's not appearing in the shop for some reason still does it take time or should it be instant.  also does that error false not mean anything significant I would of thought that's where the problem is still ...could it be an issue with the database maybe arrr this is so frustrating it's probably something minor I've done wrong. thank you for your help at least there is no error anymore

**Comment by ManicModder** [comment]
I think it may be an issue with the shop command not the add item command maybe like something to do with the data not be stored and synced properly or not being accessed properly because when I try to add other items when I look in the database it only has the one item stored and it's almost as if the shop command doesn't even try to access the database

**Comment by BIntelligent** [comment]
trust me its updateInventory function error.

**Comment by ManicModder** [comment]
Okay so do you have any idea why it might be happening and how to fix it?

**Comment by crizmo** [comment]
i been facing that issue too , u add item using the commands but the shop command doesnt show the items right
i tried updating my mongo srv and all still the same
i tried multiple even tried doing the same by using be intelligents example bot still the same issue 
so idk whats causing it too

**Comment by BIntelligent** [comment]
you should update bot than try the commands :)

**Comment by ManicModder** [comment]
I didn't think you meant that to both of us but I updated it again and it's all working now thank you so much for the assistance in this matter.

**Comment by BIntelligent** [comment]
glad it worked.
