### ISSUE TITLE
throw new RangeError('BITFIELD_INVALID', bit);

### ISSUE THREAD

**Issue by loganmulligan100** [BIntelligent/currency-system#19]
I have looked around seems to be a permissions thing although it seems to only not work when the command uses a currency-system command, every other command works perfectly, and when Im on my main account it works but for other people it just crashes with this error 
![image](https://user-images.githubusercontent.com/66179086/169673778-d3382f0e-e9be-4112-82ac-32a3fb684cc9.png)
Although for some reason it works for me and it sometimes work depending on the roles of person that is using the command, although it shouldn't because to use the command you just need to have the send_messages permission. Idk why exactly its happening, so I was wondering if anyone here could help. also, permissions are correct unless I'm missing some random thing. although it works for me no matter what role, and certain other roles but even if the roles are the exact same  it will just not work.

**Comment by loganmulligan100** [comment]
![image](https://user-images.githubusercontent.com/66179086/169673861-29f799c7-aa05-48d7-87db-4e923203f693.png)
this is it working for me, I know it says undefined I know how to fix just haven't yet as this is a bigger problem, also this happens with every command.

**Comment by loganmulligan100** [comment]
update it seems to be that you have to have admin permissions to use the commands? IDK why, If I find how to change I will let you know

**Comment by loganmulligan100** [comment]
![image](https://user-images.githubusercontent.com/66179086/169674843-21fbc3b5-8d6b-46b1-b65b-88a2ceff7e5b.png)
Whelp, this Is what I get for copying the module export part error was userpermissions should have been permission 
![image](https://user-images.githubusercontent.com/66179086/169674866-df4ea225-b0a4-4d90-a910-d236a0c20d4f.png)

**Comment by BIntelligent** [comment]
glad to know people still know to to debug errors.
