### ISSUE TITLE
Add "giveItem()"

### ISSUE THREAD

**Issue by Nex2944** [BIntelligent/currency-system#21]
A function where users can send items to each other!

Example:
```js
cs.giveItem({
   item: Item,
   amount: Number,
   user: UserResolvable,
   user2: UserResolvable,
})
```

**Comment by BIntelligent** [comment]
That's a good idea but why on earth would you make this as an "issue"

**Comment by Nex2944** [comment]
because thats what people usually do in other repos? (using labels)
