### ISSUE TITLE
Add support to TypeScript? 

### ISSUE THREAD

**Issue by GillHoang** [BIntelligent/currency-system#23]
hmm

**Comment by BIntelligent** [comment]
I don't know Typescript 😭

**Comment by GillHoang** [comment]
> I don't know Typescript 😭

 TypeScript (ts) may help you a lot, easy to use :v or i will help you add support to ts

**Comment by BIntelligent** [comment]
If someone is willing to add ts support, they can make a pull request and
add it via that. That would help everyone out!
