### ISSUE TITLE
Cannot remove shop item

### ISSUE THREAD

**Issue by ShikoShintaro** [BIntelligent/currency-system#3]
So when i try to execute removeitem (it removes but the shop dosent update) is this a bug or smth?
unless if i remove the item form the database it

**Comment by BIntelligent** [comment]
Show me what code are you using. and mongo takes atlesst 5 seconds before it updates.

**Comment by ShikoShintaro** [comment]
![image](https://user-images.githubusercontent.com/72778620/122626116-2d381f00-d0db-11eb-9b74-7114393df45c.png)

**Comment by ShikoShintaro** [comment]
this is the code i used 
its the same as yours but i changed it

**Comment by ShikoShintaro** [comment]
![image](https://user-images.githubusercontent.com/72778620/122626209-a0419580-d0db-11eb-9430-391a211cd823.png)

**Comment by BIntelligent** [comment]
Wdym by it removes shop item but dosnt update? Donst shop command when re executed removed the item? For mongo compass you need to reload to get latest changes

**Comment by ShikoShintaro** [comment]
when i tried to execute removeitem <itemnumber> it says that it removes but when i tried to execute shop command  the one i tried to remove it dosent remove the item it stays there

**Comment by BIntelligent** [comment]
Ok I'll look into it. And soon publish a fix. thanks for the report.

**Comment by ShikoShintaro** [comment]
Haiiiii~~~ thank you~

**Comment by BIntelligent** [comment]
Hai can you try to see if it's fixed or no

**Comment by ShikoShintaro** [comment]
haiii imma try to code now

**Comment by ShikoShintaro** [comment]
![image](https://user-images.githubusercontent.com/72778620/123919517-96f7d900-d9b7-11eb-8ab2-e489dfac8ed3.png)
soo uhhh when i try o execute this problem pops up

**Comment by BIntelligent** [comment]
thanks I'll look into it

**Comment by ShikoShintaro** [comment]
haiiii~~~

**Comment by BIntelligent** [comment]
ye?

**Comment by ShikoShintaro** [comment]
how did it go?

**Comment by BIntelligent** [comment]
try it now

**Comment by ShikoShintaro** [comment]
umm still the same

**Comment by ShikoShintaro** [comment]
![image](https://user-images.githubusercontent.com/72778620/124000525-3fcd2500-da06-11eb-825c-7705bd779789.png)
this problem

**Comment by BIntelligent** [comment]
actually im busy with life right now so sorry i couldn't fix it asap it might take a week sorry

**Comment by ShikoShintaro** [comment]
haiii~~~ i understand~

**Comment by BIntelligent** [comment]
i tested it now and its working fine
