### ISSUE TITLE
your mongodb uri is exposed

### ISSUE THREAD

**Issue by ghost** [BIntelligent/currency-system#8]
Hi saw your code and saw a [mongodb uri of your database](https://github.com/BIntelligent/currency-system/blob/main/src/classes/db.json). Is it meant to be exposed or no. If it's not meant to be exposed, please ignore it before someone can access your database.

**Comment by BIntelligent** [comment]
omg its so ankoying gitignore is not filtering it out its 3rd time now

**Comment by BIntelligent** [comment]
what can i do? https://github.com/BIntelligent/currency-system/blob/main/.gitignore

**Comment by ghost** [comment]
check this [article](https://stackoverflow.com/questions/45400361/why-is-gitignore-not-ignoring-my-files/45400404) out.

**Comment by ghost** [comment]
you can also create an environment variable if you want 😄

**Comment by ghost** [comment]
**This is what a person said in the article:**

The .gitignore file ensures that files not tracked by Git remain untracked.

Just adding folders/files to a .gitignore file will not untrack them -- they will remain tracked by Git.

To untrack files, it is necessary to remove from the repository the tracked files listed in .gitignore file. Then re-add them and commit your changes.

The easiest, most thorough way to do this is to remove and cache all files in the repository, then add them all back. All folders/files listed in .gitignore file will not be tracked. From the top folder in the repository run the following commands:

```
git rm -r --cached .
git add .
```
Then commit your changes:

```
git commit -m "Untrack files in .gitignore"
```
